<?php
/**
 * Attogram Games
 * https://github.com/attogram/games
 *
 * The Ordered List of Games
 */

$games = [
    'hextris-lite' => [
        'name'    => 'Hextris',
        'tag'     => 'hexagonal tetris',
        'license' => 'GPL-3.0',
        'git'     => 'https://github.com/attogram/hextris-lite.git',
        'mobile'  => true,
        'desktop' => true,
    ],
    'pond' => [
        'name'    => 'The Pond',
        'tag'     => 'eat, swim, love',
        'license' => 'GPL-3.0',
        'git'     => 'https://github.com/attogram/pond-lite.git',
        'mobile'  => true,
        'desktop' => true,
    ],
    '2048-lite' => [
        'name'    => '2048',
        'tag'     => '2, 4, 8, swipe',
        'license' => 'MIT',
        'git'     => 'https://github.com/attogram/2048-lite.git',
        'mobile'  => true,
        'desktop' => true,
    ],
    'taptaptap' => [
        'name'    => 'Tap Tap Tap',
        'tag'     => 'tap the blue',
        'license' => 'MIT',
        'git'     => 'https://github.com/MahdiF/taptaptap.git',
        'index'   => 'play/',
        'mobile'  => true,
        'desktop' => true,
    ],
    'particle-clicker' => [
        'name'    => 'Particle Clicker',
        'tag'     => 'be like CERN',
        'license' => 'MIT',
        'git'     => 'https://github.com/particle-clicker/particle-clicker.git',
        'mobile'  => true,
        'desktop' => true,
    ],
    'tower' => [
        'name'    => 'Tower',
        'tag'     => 'build up',
        'license' => 'MIT',
        'git'     => 'https://github.com/iamkun/tower_game.git',
        'mobile'  => true,
        'desktop' => true,
    ],
    'hexgl-lite' => [
        'name'    => 'HexGL',
        'tag'     => 'racing pod',
        'license' => 'MIT',
        'git'     => 'https://github.com/attogram/HexGL-lite.git',
        'mobile'  => false,
        'desktop' => true,
    ],
    '3d.city' => [
        'name'    => '3d.city',
        'tag'     => 'be the mayor',
        'license' => 'GPL-3.0',
        'git'     => 'https://github.com/lo-th/3d.city.git',
        'mobile'  => false,
        'desktop' => true,
    ],
    'clumsy-bird' => [
        'name'    => 'Clumsy Bird',
        'tag'     => 'flappy happy',
        'license' => 'GPL-3.0',
        'git'     => 'https://github.com/ellisonleao/clumsy-bird.git',
        'mobile'  => true,
        'desktop' => true,
    ],
    'fire-n-ice' => [
        'name'    => 'Fire \'n Ice',
        'tag'     => 'move the ice',
        'license' => 'MIT',
        'git'     => 'https://github.com/eugenioenko/fire-n-ice.git',
        'mobile'  => true,
        'desktop' => true,
    ],
    'paint-run' => [
        'name'    => 'Paint Run',
        'tag'     => 'paint it all blue',
        'license' => 'MIT',
        'git'     => 'https://github.com/attogram/paint-run2.git', // temp
        //'git'     => 'https://github.com/ahl389/paint-run2.git',
        'branch'  => 'gh-pages',
        'mobile'  => false,
        'desktop' => true,
    ],
    'hyperspace-garbage-collection' => [
        'name'    => 'Hyperspace G',
        'tag'     => 'collect garbage',
        'license' => 'MIT',
        'git'     => 'https://github.com/razh/game-off-2013',
        'mobile'  => true,
        'desktop' => true,
    ],
    'pacman-lite' => [
        'name'    => 'pacman',
        'tag'     => 'another pacman',
        'license' => 'GPL-3.0',
        'git'     => 'https://github.com/attogram/pacman-lite.git',
        'mobile'  => true,
        'desktop' => true,
    ],
    'the-house' => [
        'name'    => 'The House',
        'tag'     => 'Explore your home',
        'license' => 'MIT',
        'git'     => 'https://github.com/arturkot/the-house-game.git',
        'mobile'  => false,
        'desktop' => true,
    ],
    'dead-valley' => [
        'name'    => 'Dead Valley',
        'tag'     => 'survival',
        'license' => 'CC-BY-NC-4.0',
        'git'     => 'https://github.com/dmcinnes/dead-valley.git',
        'mobile'  => false,
        'desktop' => true,
    ],
    'classic-pool' => [
        'name'    => 'Pool',
        'tag'     => 'classic 8-ball',
        'license' => 'MIT',
        'git'     => 'https://github.com/henshmi/Classic-Pool-Game.git',
        'mobile'  => false,
        'desktop' => true,
    ],
    'twisty-polyhedra' => [
        'name'    => 'Twisty P',
        'tag'     => 'polyhedra turning',
        'license' => 'GPL-3.0',
        'git'     => 'https://github.com/aditya-r-m/twisty-polyhedra.git',
        'mobile'  => false,
        'desktop' => true,
    ],
    'raging-gardens' => [
        'name'    => 'Raging Gardens',
        'tag'     => 'farting ninja rabbits',
        'license' => 'MIT',
        'git'     => 'https://github.com/alunix/RagingGardensFB.git',
        'mobile'  => false,
        'desktop' => true,
    ],
    'underrun' => [
        'name'    => 'Underrun',
        'tag'     => 'run &amp; fight',
        'license' => 'MIT',
        'git'     => 'https://github.com/phoboslab/underrun.git',
        'index'   => 'index-debug.html',
        'mobile'  => false,
        'desktop' => true,
    ],
    'snakisms' => [
        'name'    => 'Snakisms',
        'tag'     => 'philosophy snake',
        'license' => 'CC-BY-NC-3.0',
        'git'     => 'https://github.com/pippinbarr/SNAKISMS.git',
        'branch'  => 'clean',
        'mobile'  => true,
        'desktop' => true,
    ],
    'html5-hearts' => [
        'name'    => 'Hearts',
        'tag'     => 'card game',
        'license' => 'BSD-3-Clause',
        'git'     => 'https://github.com/yyjhao/html5-hearts.git',
        'mobile'  => false,
        'desktop' => true,
    ],
    'EightQueens' => [
        'name'    => 'Eight Queens',
        'tag'     => 'chess puzzle',
        'license' => 'MIT',
        'git'     => 'https://github.com/attogram/EightQueens.git',
        'branch'  => 'gh-pages',
        'mobile'  => true,
        'desktop' => true,
    ],
    'chess' => [
        'name'    => 'Chess',
        'tag'     => 'e2 to e4',
        'license' => 'MIT',
        'git'     => 'https://github.com/attogram/chess.git',
        'mobile'  => true,
        'desktop' => true,
    ],
    'mah-jongg' => [
        'name'    => 'Mah-jongg',
        'tag'     => 'Tianjin 天津麻将',
        'license' => 'GPL-3.0',
        'git'     => 'https://github.com/tiansh/tjmj.git',
        'mobile'  => false,
        'desktop' => true,
    ],
    'html5-asteroids' => [
        'name'    => 'Asteroids',
        'tag'     => 'retro asteroids',
        'license' => 'MIT',
        'git'     => 'https://github.com/dmcinnes/HTML5-Asteroids.git',
        'mobile'  => false,
        'desktop' => true,
    ],
    'missile-game' => [
        'name'    => 'Missile Game',
        'tag'     => 'fly thru it',
        'license' => 'AGPL-3.0',
        'git'     => 'https://github.com/bwhmather/missile-game.git',
        'mobile'  => true,
        'desktop' => true,
    ],
    'ns-shaft' => [
        'name'    => 'NS-Shaft',
        'tag'     => 'fall safely',
        'license' => 'Apache-2.0',
        'git'     => 'https://github.com/iPel/NS-SHAFT.git',
        'mobile'  => true,
        'desktop' => true,
    ],

    // Playgrounds
    'colorful-life' => [
        'name'    => 'Colorful Life',
        'tag'     => 'life with color',
        'license' => 'GPL-3.0',
        'git'     => 'https://github.com/jaxry/colorful-life.git',
        'mobile'  => true,
        'desktop' => true,
    ],
    'life' => [
        'name'    => 'Life',
        'tag'     => 'conway\'s game',
        'license' => 'BSD-2-Clause',
        'git'     => 'https://github.com/copy/life.git',
        'mobile'  => true,
        'desktop' => true,
    ],


    // Musical Instruments
    'javascript-piano' => [
        'name'    => 'Piano J',
        'tag'     => 'synthy javascript',
        'license' => 'MIT',
        'git'     => 'https://github.com/mrcoles/javascript-piano.git',
        'mobile'  => true,
        'desktop' => true,
    ],
    'virtual-piano' => [
        'name'    => 'Piano V',
        'tag'     => 'virtually classic',
        'license' => 'GPL-3.0',
        'git'     => 'https://github.com/otanim/virtual-piano.git',
        'mobile'  => true,
        'desktop' => true,
    ],
    'chordomatic' => [
        'name'    => 'Chordomatic',
        'tag'     => 'guitar strumming',
        'license' => 'GPL-3.0',
        'git'     => 'https://github.com/kiprobinson/chordomatic.git',
        'index'   => 'app/chord-player.html',
        'mobile'  => true,
        'desktop' => true,
    ],
];
